# Site settings
title: "CV de Michelle A."
description: "Mon CV sous Jekyll & GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Michelle AVOMO E."
resume_title:                   "Fullstack software crafter Senior"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "michelle.avomo@proton.me"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+33 6 4* ** ** *2"
resume_contact_address:         "Paris"

resume_header_contact_info:     "Paris • +33 6 4* ** ** *2 • michelle.***@proton.me"
display_header_contact_info:    "false"

resume_header_intro: "<p>Diplômée 2012, j'ai démarré ma vie professionnelle comme développeuse Java puis Front étant passée par Backbone.js, AngularJS, Angular puis VueJS. Ravie d'avoir retrouvé le monde du back-end par de la conception d'APIs en Kotlin depuis 2021. </p>
 <p> Je m'intérresse actuellement aux outils soutenant la culture DevOps, aux enjeux de la cybersécurité et autres domaines complémentaires du génie logiciel intégrant de la complexité technique et/ou fonctionnelle. </p> <p>Je vis et travaille à Paris.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true  
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mavomo"
  resume_linkedin_url:          "https://www.linkedin.com/in/michelle-a-622b8858"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
